### ISSUE TITLE
rename can break seek(SeekFrom(End()))

### ISSUE THREAD

**Issue by dickeycl** [Xuanwo/hdrs#108]
Seek to end reads file metadata to determine the file length. If the file has been renamed between the open and the seek, the seek will fail. If the file has been renamed and the original name has been reused, the seek may succeed but point to the wrong position.

A couple of options:

read file metadata (size, last modification time)
open the file
reread file metadata (size, last modification time)
fail the open of the values from step 1 and step 3 do not match.
(Relies on hdfsSeek returning an error for seeking beyond end of file. That seems to be the case, but is not documented.)

read file metadata (size)
open the file
perform a search (series of calls to hdfsSeek) to determine the actual file size, using the size value from step 1 as a hint.
Either one seems like a lot of work to get a value which HDFS probably knows internally.

**Comment by Xuanwo** [comment]
HDFS currently lacks native support for seeking to the end. We added this feature for ease of use, but it appears that we should consider removing it.
