### ISSUE TITLE
Concurrent write failed

### ISSUE THREAD

**Issue by zuston** [Xuanwo/hdrs#113]
After initializing one client of hdfs, system will hang when using the same client to concurrent write.

**Comment by Xuanwo** [comment]
Hi, could you please provide a reproduction?

**Comment by zuston** [comment]
sorry, I just test directly in our cluster. please see https://github.com/zuston/uniffle-x/blob/88b6e5cfe34e97214f278744bd342673086eb206/src/store/hdfs.rs#L119

I'm not sure whether the invoking of hdrs is wrong, could you help review this?

**Comment by Xuanwo** [comment]
Seems you will hold the lock https://github.com/zuston/uniffle-x/blob/88b6e5cfe34e97214f278744bd342673086eb206/src/store/hdfs.rs#L86C42-L86C42 for the entire function call.

Can you try reproducing this hang by directly calling `hdrs::Client`? This will help us confirm whether the issue is with hdrs or not.

**Comment by zuston** [comment]
Sorry for late reply, I missed this thread

> Seems you will hold the lock https://github.com/zuston/uniffle-x/blob/88b6e5cfe34e97214f278744bd342673086eb206/src/store/hdfs.rs#L86C42-L86C42 for the entire function call.

yes. This is to keep unique for one partition writing. I don't think it's the root cause.

> Can you try reproducing this hang by directly calling hdrs::Client? This will help us confirm whether the issue is with hdrs or not.

Yes. I reproduce this in our internal cluster. And I add some debug log to find the blocking is always happened in https://github.com/zuston/uniffle-x/blob/88b6e5cfe34e97214f278744bd342673086eb206/src/store/hdfs.rs#L119 

But I'm not sure whether this will block the tokio scheduler. Like this? https://github.com/tokio-rs/tokio/issues/4730

**Comment by Xuanwo** [comment]
`self.filesystem.append()` did a lot of operations, can you go deep to find out which part hang? `self.client.metadata()` is a blocking call, try call it inside [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) instead.

**Comment by zuston** [comment]
Sorry, after test with several times, I think it is caused by the tokio hang. But I still don’t know what make this. 

> `self.filesystem.append()` did a lot of operations, can you go deep to find out which part hang?
> 
> `self.client.metadata()` is a blocking call, try call it inside [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) instead.

Tested. Not the root cause

**Comment by Xuanwo** [comment]
> I think it is caused by the tokio hang

Most of the time, tokio hang is caused by unexpected blocking call in async fucntions.

**Comment by zuston** [comment]
> > I think it is caused by the tokio hang
> 
> Most of the time, tokio hang is caused by blocking call in async fucntions.

Thanks for your explanation. Let me take a try

**Comment by zuston** [comment]
After testing with risingwave/await-tree, I think there are too much waiting tasks to make tokio hang rather than hdrs .

Sorry for that, let's close this.
