### ISSUE TITLE
hdrs: Error: Command failed

### ISSUE THREAD

**Issue by Ilqjx** [Xuanwo/hdrs#73]
Hi, how can I fix this error?

Errors
hdrs: Error: Command failed: git --no-pager --git-dir="/home/qiaojia/.cargo/registry/index/github.com-1ecc6299db9ec823/.git" show origin/master:hd/rs/hdrs
fatal: invalid object name 'origin/master'.

![image](https://user-images.githubusercontent.com/53934234/178963665-abe87ac2-b318-417d-ab4d-68cb56fb30d3.png)

**Comment by Ilqjx** [comment]
ENV
Ubuntu 22.04 LTS
Java 18.0.1.1
Hadoop 3.3.3
rustc 1.62.0

**Comment by Xuanwo** [comment]
Thanks for reporting!

Do you have Hadoop setup correctly?

For verification, you can run the following command:

```shell
hdfs dfs -ls / --loglevel DEBUG
```

**Comment by Ilqjx** [comment]
If this is the case, the installation should be successful.

![image](https://user-images.githubusercontent.com/53934234/179166337-335ee923-5d8b-44be-8719-9d0827e64f2c.png)

Is it recommended to use this crate in a production environment?

**Comment by Ilqjx** [comment]
When I only have this line of code, it also gives an error. I tested it and my hadoop has no problem.

![image](https://user-images.githubusercontent.com/53934234/179178205-4d0108cc-9aa1-42f1-bbee-263c0b85175a.png)

![image](https://user-images.githubusercontent.com/53934234/179178251-6f43153e-bef8-4a1d-acb0-80318fe4f6cd.png)

**Comment by Xuanwo** [comment]
> Is it recommended to use this crate in a production environment?

`hdrs` should work well on the happy path, but it doesn't pass any battle in the production environment.

> ENV:
> Ubuntu 22.04
> Java 18.0.1.1
> Hadoop 3.3.3
> rustc 1.62.0

Maybe we are using too old APIs, please try update this issue:

```shell
hdfs-sys = { version = "0.2.0", features = ["hdfs_3_3"] }
```

I believe this will give more information for debugging.

**Comment by Ilqjx** [comment]
Thanks for your help.
