### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.security.UserGroupInformation

### ISSUE THREAD

**Issue by Ilqjx** [Xuanwo/hdrs#74]
Please, how should this problem be solved?

![image](https://user-images.githubusercontent.com/53934234/179653541-9a136957-3566-407a-824f-ff3dac893b5b.png)

**Comment by Xuanwo** [comment]
Duplicate with https://github.com/datafuselabs/opendal/issues/448
