### ISSUE TITLE
Discussion about append

### ISSUE THREAD

**Issue by Ilqjx** [Xuanwo/hdrs#75]
When the file does not exist, `append(true)` will result in the error `Failed to append to non-existent file`.

I think `append(true)` should not report an error when the file does not exist, but instead behave as appending to a 0-length file.

```rust
let mut file = client
        .open_file()
        .write(true)
        .create(true)
        .append(true)
        .open(path.as_str())
        .unwrap();
```

**Comment by Xuanwo** [comment]
hdrs just convert `OpenOptions` to `libc::{O_CREAT,...}`, there are very few things we can do here.

Does hdfs has the same behavior?

**Comment by Ilqjx** [comment]
Sorry, I don't know if hdfs has the same behavior.
