### ISSUE TITLE
Support kerberos authentication?

### ISSUE THREAD

**Issue by Ilqjx** [Xuanwo/hdrs#77]

**Comment by Xuanwo** [comment]
hdrs doesn't support Kerberos authentication so far. It even doesn't support username/password auth.

We can implement those features via

- hdfs_sys::hdfsBuilderConnect
- hdfs_sys::hdfsBuilderSetUserName
- hdfs_sys::hdfsBuilderSetKerbTicketCachePath

We can replace `hdfsConnect` with `hdfsBuilderXxxx` APIs.

If you have interested in this, welcome implement them by yourself!

**Comment by Ilqjx** [comment]
Ok, I'll try.

**Comment by Xuanwo** [comment]
We can split this task in the following steps:

- Migrate current `hdfsConnect` to `hdfsBuilderXxxx` API
- Support connect with username by `hdfsBuilderSetUserName`
- Support kerberos

**Comment by Ilqjx** [comment]
Thanks

**Comment by Xuanwo** [comment]
Should this code be like the following?

```diff
let client = Client::connect_set_kerb_ticket_cache_path(
    "hdfs://localhost:9000",
-    "/home/guozhenwei/hadoop/hadoop-3.2.4/etc/hadoop",
+    "/home/guozhenwei/hadoop/hadoop-3.2.4/etc/hadoop/hdfs.keytab",
)
```

Tips: We must check the return value of every sys call to `hdfs-sys` because they could fail at any time.

**Comment by Ilqjx** [comment]
I changed it, same error.

**Comment by Xuanwo** [comment]
Well, I know very little about neither `kerberos` nor `hdfs`'s Kerberos support.

I don't have any ideas so far...

**Comment by Ilqjx** [comment]
Okay, I'm trying to figure it out myself, thank you.

**Comment by Ilqjx** [comment]
If you have time, could you take a look at how to support kerberos authentication?

I haven't been able to solve the problem I encountered before.

```text
hdfsOpenFile(/hello/hello.txt): FileSystem#append((Lorg/apache/hadoop/fs/Path;)Lorg/apache/hadoop/fs/FSDataOutputStream;) error:
(unable to get stack trace for org.apache.hadoop.security.AccessControlException exception: ExceptionUtils::getStackTrace error.)
test client::tests::test_connect_set_kerb_ticket_cache_path ... FAILED

failures:

---- client::tests::test_connect_set_kerb_ticket_cache_path stdout ----
b is null: true
thread 'client::tests::test_connect_set_kerb_ticket_cache_path' panicked at 'Failed to open file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/client.rs:528:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Xuanwo** [comment]
Thanks for the trying!

And, I'm sorry that I'm a bit busy these days. I will look into this issue at some day which I can give a promise.

**Comment by Ilqjx** [comment]
Thank you for your promise.

**Comment by agardenat** [comment]
Hi,It works for me when KRB5CCNAME is correctly set up.

**Comment by timvinc** [comment]
I got @Ilqjx  's code to work as well.  The cache name can't point to a keytab file, it needs to point to a ticket cache.  I found the location of mine by running 'klist' after 'kinit' and it looks something like:

Ticket cache: FILE:/tmp/krb5cc_1234567890
Default principal: user.name@domain

Valid starting       Expires              Service principal
12/16/2022 01:01:01  12/17/2022 01:01:01  krbtgt/domain@domain

**Comment by Xuanwo** [comment]
> The cache name can't point to a keytab file, it needs to point to a ticket cache. I found the location of mine by running 'klist' after 'kinit' and it looks something like:

Thanks for the investigating! Are you willing to send a PR to document how to setup kerberos correctly? I know nothing about it :cry:

**Comment by agardenat** [comment]
> > The cache name can't point to a keytab file, it needs to point to a ticket cache. I found the location of mine by running 'klist' after 'kinit' and it looks something like:
> 
> Thanks for the investigating! Are you willing to send a PR to document how to setup kerberos correctly? I know nothing about it cry

Depending on the kerberos configuration, tipycally /etc/krb5.conf, you have the cache set to something like :

`FILE:/tmp/krb5cc_$UID`

You got a kerberos ticket in this cache when you kinit from a keytab or principal/password : 

```
kinit -k -t principal@domain.keytab  principal@domain
or
kinit principal@domain
```

And so it works fine when etting the environment variable KRB5CCNAME like this, and having an active  kerberos ticket in the cache : 
`
export KRB5CCNAME=FILE:/tmp/krb5cc_$UID`

Tested on hdfs from CDH 6 and CDP Public, and also with adls gen2 (ABFS://) from CDP public.

**Comment by Xuanwo** [comment]
Thanks to @zuston's effort, this feature has been added.
